controller_manager: 
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont: 
    type: diff_drive_controller/DiffDriveController

    joint_broad:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters: 

    publish_rate: 35.0
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35 #CHANGE THIS TO CORRECT WHEEL SEPARATION
    wheel_radius: 0.05 #CHANGE THIS TO CORRECT WHEEL RADIUS

    use_stamped_vel: false